// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkAxF76tfdRpIs8_yVapx4iVkjQhESXz8',
    appId: '1:100479903123:web:235752e5dbe5b99756b466',
    messagingSenderId: '100479903123',
    projectId: 'en-y-1b285',
    authDomain: 'en-y-1b285.firebaseapp.com',
    storageBucket: 'en-y-1b285.appspot.com',
    measurementId: 'G-K29C95X6BE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfJrmdAV1VaoZ5B2DI3tL3OInftWKxijM',
    appId: '1:100479903123:android:8a200da79ff4e19256b466',
    messagingSenderId: '100479903123',
    projectId: 'en-y-1b285',
    storageBucket: 'en-y-1b285.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_HEr0MyIF2Xogjx5yEMLzDbTScQzcm_g',
    appId: '1:100479903123:ios:90c5f78bae68832956b466',
    messagingSenderId: '100479903123',
    projectId: 'en-y-1b285',
    storageBucket: 'en-y-1b285.appspot.com',
    iosBundleId: 'com.example.eny',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_HEr0MyIF2Xogjx5yEMLzDbTScQzcm_g',
    appId: '1:100479903123:ios:7759893cada6d6c456b466',
    messagingSenderId: '100479903123',
    projectId: 'en-y-1b285',
    storageBucket: 'en-y-1b285.appspot.com',
    iosBundleId: 'com.example.eny.RunnerTests',
  );
}
