// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhFMX5q0I3RuoLTO1qcIsjgoQM91Ry7to',
    appId: '1:930857671448:web:53b458de78cc957b171c6d',
    messagingSenderId: '930857671448',
    projectId: 'en-y-30e54',
    authDomain: 'en-y-30e54.firebaseapp.com',
    storageBucket: 'en-y-30e54.appspot.com',
    measurementId: 'G-7RHW5SJ3SN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj6-EpekfMl9BKni0-mh6Y-xl48azxW-Y',
    appId: '1:930857671448:android:ff47080cc66fb19c171c6d',
    messagingSenderId: '930857671448',
    projectId: 'en-y-30e54',
    storageBucket: 'en-y-30e54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ0r92l6wnGRpyRecTT3od8CiR8FtHJi0',
    appId: '1:930857671448:ios:8997d87aa82301fd171c6d',
    messagingSenderId: '930857671448',
    projectId: 'en-y-30e54',
    storageBucket: 'en-y-30e54.appspot.com',
    iosClientId: '930857671448-57hq0bmgkqpn02c0c92ltg6lh2irfvnt.apps.googleusercontent.com',
    iosBundleId: 'com.example.eny',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ0r92l6wnGRpyRecTT3od8CiR8FtHJi0',
    appId: '1:930857671448:ios:8997d87aa82301fd171c6d',
    messagingSenderId: '930857671448',
    projectId: 'en-y-30e54',
    storageBucket: 'en-y-30e54.appspot.com',
    iosClientId: '930857671448-57hq0bmgkqpn02c0c92ltg6lh2irfvnt.apps.googleusercontent.com',
    iosBundleId: 'com.example.eny',
  );
}
